In [401]:
import numpy as np



In [402]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])



In [403]:
a[a < 0]



array([-2, -1, -6, -7])

In [404]:
a[a > 0]



array([ 4, 10, 12, 23,  3])

In [5]:
a[(a > 0) & (a % 2 == 0)]




array([ 4, 10, 12])

In [6]:
a = np.array(a)
a + 3 



array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [405]:
sum_3 = a[(a+3) > 0]

len(sum_3)

10

In [406]:
squared = a ** 2




In [407]:
squared




array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [408]:
a.mean()



3.0

In [10]:
a.std()




144.0243035046516

In [411]:
center_a = a - 3

center_a



array([  1,   7,   9,  20,  -5,  -4,  -3,  -3,  -3,  -9,   0, -10])

In [12]:
import pandas as pd
import scipy.stats as stats




In [410]:
stats.zscore(a)




array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [123]:
# Life w/o numpy to life with numpy

## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Use python's built in functionality/operators to determine the following:




In [15]:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

sum_of_a = sum(a)

sum_of_a



55

In [16]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

min_of_a = min(a)

min(a)



1

In [17]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

max_of_a = max(a)

max(a)



10

In [35]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

len_of_a = len(a)
sum_of_a = sum(a)
mean_of_a = sum_of_a / len_of_a
  
print(mean_of_a)




5.5


In [139]:
# Exercise 6 - Make a variable named squares_of_a.
#it should hold each number in a squared like [1, 4, 9, 16, 25...]

squared_of_a = [x**2 for x in a]

squared_of_a


[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [78]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

odds_in_a = []
for x in a:
        if x % 2 != 0:
            odds_in_a.append(x)
print(odds_in_a)



[1, 3, 5, 7, 9]


In [72]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

evens_in_a = []
for x in a:
        if x % 2 == 0:
            evens_in_a.append(x)
print(evens_in_a)



[2, 4, 6, 8, 10]


In [370]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares 
#for this list of two lists.

b = [
    [3, 4, 5],
    [6, 7, 8]
]


min(b[0]), max(b[1]), sum((b[1]) + (b[0])), sum((b[1]) + (b[0])) / 6



(3, 8, 33, 5.5)

In [184]:
squared_of_b = [x**2 for x in b[0] + b[1]]

squared_of_b

[9, 16, 25, 36, 49, 64]

In [215]:
product_of_b = [product_of_b * x for x in b[0] + b[1]]



In [381]:
np.product(b)

20160

In [ ]:
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)
    
sum_of_b

In [357]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. 
#**Hint, you'll first need to make sure that the "b" variable is a numpy array**


b = np.array(b)


sum((b[0]) + (b[1]))


In [211]:
# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

min_of_b



3

In [371]:
np.min(b)




3

In [210]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])


max_of_b


8

In [372]:
np.max(b)



8

In [212]:
# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

mean_of_b

5.5

In [373]:
np.mean(b)



5.5

In [374]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
        
product_of_b

20160

In [375]:
np.product(b)




20160

In [377]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
        
squares_of_b

[9, 16, 25, 36, 49, 64]

In [376]:
np.square(b)





array([[ 9, 16, 25],
       [36, 49, 64]])

In [378]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
            
odds_in_b           

[3, 5, 7]

In [396]:
b = np.array(b)

odds_in_b = b[(b % 2 == 1)]

odds_in_b

array([3, 5, 7])

In [368]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
            
evens_in_b            

[0, 2, 4]

In [397]:
b = np.array(b)

evens_in_b = b[(b % 2 == 0)]

evens_in_b

array([4, 6, 8])

In [216]:
# Exercise 9 - print out the shape of the array b.

b.shape

(2, 3)

In [412]:
# Exercise 10 - transpose the array b.

transpose_b = np.transpose(b)

transpose_b

array([[3, 6],
       [4, 7],
       [5, 8]])

In [413]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

b.reshape(1,6)

array([[3, 4, 5, 6, 7, 8]])

In [415]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

np.reshape(b,(6,1))

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [275]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
# Exercise 1 - Find the min, max, sum, and product of c.
c = np.array(c)

np.min(c), np.max(c), np.sum(c), np.product(c)

(1, 9, 45, 362880)

In [276]:
# Exercise 2 - Determine the standard deviation of c.

c.std()

2.581988897471611

In [277]:
# Exercise 3 - Determine the variance of c.

c.var()

6.666666666666667

In [278]:
# Exercise 4 - Print out the shape of the array c

c.shape

(3, 3)

In [417]:
# Exercise 5 - Transpose c and print out transposed result.

transpose_c = c.transpose()

transpose_c

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [285]:
# Exercise 6 - Get the dot product of the array c with c. 

np.dot(c, c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [418]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

cat = transpose_c * c

np.sum(cat)

261

In [287]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. 
#Answer should be 131681894400.

np.product(c * c.transpose())

131681894400

In [303]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

d = np.array(d)

In [307]:
# Exercise 1 - Find the sine of all the numbers in d

np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [308]:
# Exercise 2 - Find the cosine of all the numbers in d

np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [309]:
# Exercise 3 - Find the tangent of all the numbers in d

np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [423]:
# Exercise 4 - Find all the negative numbers in d

neg_d = d < 0

neg_d


array([[False, False, False, False, False, False],
       [False,  True,  True, False, False, False],
       [False, False,  True, False,  True, False]])

In [313]:
# Exercise 5 - Find all the positive numbers in d

d[~(d < 1)]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [324]:
# Exercise 6 - Return an array of only the unique numbers in d.

np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [326]:
# Exercise 7 - Determine how many unique numbers there are in d.

len(np.unique(d))

11

In [314]:
# Exercise 8 - Print out the shape of d.

d.shape

(3, 6)

In [317]:
# Exercise 9 - Transpose and then print out the shape of d.

d.transpose().shape

(6, 3)

In [343]:
# Exercise 10 - Reshape d into an array of 9 x 2

np.reshape(d,(9,2))

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])